services:
  app:
    container_name: assignment
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres  # Using service name for networking within Docker
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=assignment
      - PORT=3000
      - JWT_SECRET=123456
      - JWT_EXPIRATION=3600
      - REFRESH_TOKEN_EXPIRATION=3600
      - BASE_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - uploads:/app/uploads
    command: npm run start:dev
    depends_on:
      - postgres  # Ensures postgres starts first

  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=assignment
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  uploads:
    driver: local
